### ISSUE TITLE
Subscribe to "run" instead of checking "--watch"

### ISSUE THREAD

**Issue by Strate** [TiddoLangerak/webpack-fail-plugin#3]
> The run method of the Compiler is used to start a compilation. This is not called in watch mode.
> https://webpack.github.io/docs/plugins.html

Checking for `process.argv.indexof("--watch")` is not good. Because there is an alias `-w` and watch can be set in config. More proper way to check that is it non-watching mode is subscribing to `run` event.

**Comment by TiddoLangerak** [comment]
Long overdue, but closed via #4

**Comment by TiddoLangerak** [comment]
And published with 1.0.5
